# Site settings
title: Jon Thornton | Software Engineer
email: jon.thornton07@gmail.com
description: Official website for Jon Thornton, Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.jonthornton.org" # the base hostname & protocol for your site
twitter_username: jthornton07
github_username:  jonthornton07

# Build settings
markdown: kramdown
